apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
  - reviews
  http:
  - match:
    - headers:
        end-user:
          exact: jason
    route:
    - destination:
        host: reviews
        subset: v2
  - route:
    - destination:
        host: reviews
        subset: v1
      weight: {{ .Values.Deployment.Reviews.v1.Weight }}
    - destination:
        host: reviews
        subset: v3
      weight: {{ .Values.Deployment.Reviews.v3.Weight }}